Repository microsoft/vscode-python-environments, pull requests merged in 2024-12, with the labels that each got.

#80 Fix for conda listing in README.
  README.md
Labels: bug, documentation

#85 Turn on nightly scheduled builds
  build/azure-pipeline.pre-release.yml
Labels: debt

#84 Fix bug with `pip list` parsing
  src/extension.ts
  src/managers/builtin/cache.ts
  src/managers/builtin/helpers.ts
  src/managers/builtin/main.ts
  src/managers/builtin/pipListUtils.ts
  src/managers/builtin/pipManager.ts
  src/managers/builtin/sysPythonManager.ts
  src/managers/builtin/utils.ts
  src/managers/builtin/uvProjectCreator.ts
  src/managers/builtin/venvManager.ts
  src/managers/builtin/venvUtils.ts
  src/test/constants.ts
  src/test/managers/builtin/pipListUtils.unit.test.ts
  src/test/managers/builtin/piplist1.actual.txt
  src/test/managers/builtin/piplist1.expected.json
  src/test/managers/builtin/piplist2.actual.txt
  src/test/managers/builtin/piplist2.expected.json
Labels: bug

#81 Fix when clause for activate/deactivate button
  README.md
  package.json
  package.nls.json
Labels: bug

#87 Filter and remove folders from auto-find already in projects
  src/common/localize.ts
  src/common/utils/asyncUtils.ts
  src/extension.ts
  src/features/creators/autoFindProjects.ts
  src/features/creators/existingProjects.ts
  src/features/creators/projectCreators.ts
  src/features/projectCreators.ts
  src/test/features/creators/autoFindProjects.unit.test.ts
Labels: bug

#97 Ensures development mode ids are calculated from development path
  src/api.ts
  src/common/extension.apis.ts
  src/common/extensions.apis.ts
  src/common/utils/frameUtils.ts
  src/features/envManagers.ts
Labels: bug
