Repository microsoft/vscode-python-environments, pull requests merged in 2025-04, with the labels that each got.

#181 chore: refactor common shell execution code
  src/features/terminal/terminalActivationState.ts
Labels: debt

#263 fix: for venv common packages shows installed packages pre ticked
  src/managers/builtin/pipManager.ts
  src/managers/builtin/pipUtils.ts
  src/managers/common/pickers.ts
Labels: bug

#264 fix: filter telemetry from in development extensions
  src/features/envManagers.ts
Labels: bug

#265 feat: add "Quick Create" option for venvs
  src/common/localize.ts
  src/managers/builtin/venvUtils.ts
Labels: feature-request

#269 feat: telemetry when using quick create
  src/common/telemetry/constants.ts
  src/managers/builtin/venvUtils.ts
Labels: feature-request

#271 fix: bug with `filePath` when finding calling extension
  src/common/utils/frameUtils.ts
  src/common/utils/pathUtils.ts
Labels: bug

#279 feat: improve package management
  examples/sample1/src/api.ts
  package-lock.json
  package.json
  package.nls.json
  src/api.ts
  src/common/localize.ts
  src/common/pickers/packages.ts
  src/extension.ts
  src/features/envCommands.ts
  src/features/pythonApi.ts
  src/internal.api.ts
  src/managers/builtin/pipManager.ts
  src/managers/builtin/pipUtils.ts
  src/managers/builtin/utils.ts
  src/managers/builtin/venvUtils.ts
  src/managers/common/pickers.ts
  src/managers/common/utils.ts
  src/managers/conda/condaPackageManager.ts
  src/managers/conda/condaUtils.ts
  src/vscode.proposed.terminalShellType.d.ts
Labels: feature-request

#277 fix: avoid generating multiple events for the same environment
  src/features/envManagers.ts
  src/managers/builtin/main.ts
  src/managers/builtin/venvManager.ts
Labels: bug

#287 fix: ensure script casing match for activations
  src/features/common/shellDetector.ts
  src/managers/builtin/venvUtils.ts
  src/managers/conda/condaUtils.ts
Labels: bug

#281 feat: Add support for Quick Create
  examples/sample1/src/api.ts
  examples/sample1/src/sampleEnvManager.ts
  src/api.ts
  src/common/localize.ts
  src/common/pickers/environments.ts
  src/common/pickers/managers.ts
  src/features/envCommands.ts
  src/features/pythonApi.ts
  src/internal.api.ts
  src/managers/builtin/venvManager.ts
  src/managers/builtin/venvUtils.ts
  src/managers/conda/condaEnvManager.ts
  src/managers/conda/condaUtils.ts
  src/test/features/envCommands.unit.test.ts
Labels: feature-request

#288 fix: clarify that `showSkipOption` also applies to uninstallations
  src/api.ts
Labels: bug, documentation

#290 fix: ensure 'base' conda environment is not in a group
  src/managers/conda/condaUtils.ts
Labels: bug

#283 fix: id generation for env and pkg managers
  src/common/utils/frameUtils.ts
  src/features/envManagers.ts
Labels: bug

#293 add handling for notebook-cells as inputs to API
  src/common/utils/pathUtils.ts
  src/features/pythonApi.ts
Labels: debt

#295 fix: ensure quick create is handled when using command API
  src/features/envCommands.ts
  src/managers/builtin/venvManager.ts
Labels: bug

#298 Add fix to support project root item in project getter
  src/features/envCommands.ts
Labels: bug

#308 fix: quick Create ux tweaks and clean up
  src/api.ts
  src/common/pickers/managers.ts
  src/internal.api.ts
  src/managers/builtin/venvManager.ts
  src/managers/common/utils.ts
  src/managers/conda/condaEnvManager.ts
Labels: bug

#302 feat: add telemetry for install/uninstall packages
  src/api.ts
  src/common/telemetry/constants.ts
  src/extension.ts
  src/internal.api.ts
  src/managers/builtin/pipManager.ts
  src/managers/conda/condaPackageManager.ts
Labels: feature-request

#300 feat: telemetry for select env and package managers
  src/common/telemetry/constants.ts
  src/common/telemetry/helpers.ts
  src/extension.ts
Labels: feature-request

#316 fix: detect terminal `pip installs` and refresh ui
  src/managers/builtin/main.ts
  src/managers/builtin/pipUtils.ts
Labels: bug

#322 fix: ensure path input to copilot tools correctly converted to URI
  src/common/utils/pathUtils.ts
  src/features/copilotTools.ts
  src/test/common/pathUtils.unit.test.ts
  src/test/copilotTools.unit.test.ts
Labels: bug

#314 fix: detect if extension is installed and activated for selected env/package manager
  src/api.ts
  src/common/localize.ts
  src/common/workbenchCommands.ts
  src/extension.ts
  src/features/common/managerReady.ts
  src/features/envManagers.ts
  src/features/pythonApi.ts
Labels: bug

#337 chore: refactoring and cleanup
  src/api.ts
  src/common/localize.ts
  src/features/terminal/shellStartupActivationVariablesManager.ts
  src/features/terminal/shellStartupSetupHandlers.ts
  src/features/terminal/terminalManager.ts
  src/features/terminal/utils.ts
Labels: debt

#339 fix: inconsistent shell name display
  src/features/terminal/shells/bash/bashStartup.ts
  src/features/terminal/shells/fish/fishStartup.ts
Labels: bug

#312 Get Notebook Uri from Cell Logic Fix
  src/common/utils/pathUtils.ts
Labels: bug

#362 fix: bugs where env deletion or creation are not recorded
  src/extension.ts
  src/features/views/projectView.ts
  src/managers/builtin/venvManager.ts
Labels: bug

#372 fix: quick create does not show up when there only one provider
  src/common/pickers/managers.ts
Labels: bug
