Repository microsoft/vscode-python-environments, pull requests merged in 2025-10, with the labels that each got.

#880 Fix where activation goes missing after user modifying rc scripts
  src/features/terminal/shells/bash/bashStartup.ts
  src/features/terminal/terminalManager.ts
Labels: bug

#886 fix env var clearing
  src/features/terminal/terminalEnvVarInjector.ts
Labels: bug

#890 Fix quoting logic to escape special characters in exec path
  src/features/execution/execUtils.ts
Labels: bug

#891 fix as-any linting warnings
  .github/instructions/generic.instructions.md
  eslint.config.mjs
  src/test/features/terminalEnvVarInjectorBasic.unit.test.ts
Labels: debt

#892 Revert "fix as-any linting warnings"
  .github/instructions/generic.instructions.md
  eslint.config.mjs
  src/test/features/terminalEnvVarInjectorBasic.unit.test.ts
Labels: no-changelog

#896 Fix wsl not activating properly.
  src/features/terminal/shells/bash/bashStartup.ts
  src/features/terminal/shells/common/shellUtils.ts
  src/features/terminal/shells/fish/fishStartup.ts
  src/features/terminal/shells/pwsh/pwshStartup.ts
  src/features/terminal/terminalManager.ts
Labels: bug

#897 Fix bug with getAutoActivationType
  src/features/terminal/utils.ts
  src/test/features/terminal/utils.unit.test.ts
Labels: bug

#856 feat: add back button to all necessary flows in UI
  src/common/pickers/managers.ts
  src/extension.ts
  src/helpers.ts
  src/managers/builtin/venvStepBasedFlow.ts
  src/managers/builtin/venvUtils.ts
  src/managers/conda/condaStepBasedFlow.ts
  src/managers/conda/condaUtils.ts
Labels: debt

#907 fix ts issue
  src/test/mocks/mockDocument.ts
Labels: debt

#877 add testing for runInBackground
  src/common/childProcess.apis.ts
  src/features/execution/runInBackground.ts
  src/test/features/execution/runInBackground.unit.test.ts
Labels: debt
