Repository microsoft/vscode-python-environments, pull requests merged in 2025-01, with the labels that each got.

#101 Adds group feature environment manager UI
  src/api.ts
  src/features/envCommands.ts
  src/features/views/envManagersView.ts
  src/features/views/treeViewItems.ts
  src/internal.api.ts
  src/managers/conda/condaUtils.ts
Labels: feature-request

#112 Ensure `pwsh` (powershell Core) use the right activation script
  src/managers/builtin/venvUtils.ts
Labels: bug

#113 Quote `conda env remove` arguments when using full path
  src/managers/conda/condaUtils.ts
Labels: bug

#114 Fix missing common list when no installables are available
  src/managers/builtin/pipUtils.ts
Labels: bug

#120 Adds uninstall button on packages
  package.json
  package.nls.json
  src/extension.ts
  src/features/envCommands.ts
Labels: feature-request

#126 Fix bug with updating activation state for terminal activate button
  src/features/terminal/terminalManager.ts
Labels: bug

#134 Add tooltip message to indicate selected
  src/common/localize.ts
  src/common/utils/pythonPath.ts
  src/common/window.apis.ts
  src/extension.ts
  src/features/views/envManagersView.ts
  src/features/views/treeViewItems.ts
  src/internal.api.ts
Labels: feature-request

#131 Ensure activate button is not shown on task terminals
  src/features/terminal/activateMenuButton.ts
  src/features/terminal/terminalManager.ts
  src/features/terminal/utils.ts
Labels: bug

#133 Include native finder conda when searching
  src/managers/conda/condaUtils.ts
  src/managers/conda/main.ts
Labels: bug

#145 Handle venv creation when running in no-workspace case
  src/common/pickers/projects.ts
  src/features/envCommands.ts
  src/test/copilotTools.unit.test.ts
  src/test/features/envCommands.unit.test.ts
Labels: bug

#148 remove ability to reference get_packages from prompting
  package.json
Labels: debt
