Repository microsoft/vscode-python-environments, pull requests merged in 2025-02, with the labels that each got.

#150 update release version to 0.2.0
  package-lock.json
  package.json
Labels: no-changelog

#151 update to version 0.3.0-dev
  package-lock.json
  package.json
Labels: no-changelog

#153 Adopt Terminal Shell Type API from VSCode with legacy fallback
  package.json
  src/features/common/shellDetector.ts
  src/vscode.proposed.terminalShellType.d.ts
Labels: debt

#155 Use Terminal Shell Env API to detect activations
  package.json
  src/features/terminal/terminalManager.ts
  src/vscode.proposed.terminalShellEnv.d.ts
Labels: debt

#157 Relax version check to handle >2024 versions of python extension
  src/common/extVersion.ts
Labels: bug

#152 Move copilot tools to features directory
  src/extension.ts
  src/features/copilotTools.ts
  src/test/copilotTools.unit.test.ts
Labels: debt

#154 Typos and clean up
  examples/sample1/src/api.ts
  package.json
  src/api.ts
Labels: debt

#161 Pin engine version to enable proposed features
  package-lock.json
  package.json
Labels: bug

#164 remove chat proposed API references
  package.json
  vscode.proposed.chatParticipantAdditions.d.ts
  vscode.proposed.chatParticipantPrivate.d.ts
  vscode.proposed.chatVariableResolver.d.ts
Labels: no-changelog

#160 Use activation event and shell integration for activation tracking
  src/common/utils/debounce.ts
  src/common/utils/pathUtils.ts
  src/common/window.apis.ts
  src/extension.ts
  src/features/terminal/activateMenuButton.ts
  src/features/terminal/terminalActivationState.ts
  src/features/terminal/terminalManager.ts
  src/features/terminal/utils.ts
Labels: bug

#170 feat: Add copy path to Project and Environments
  package.json
  package.nls.json
  src/common/env.apis.ts
  src/extension.ts
  src/features/envCommands.ts
  src/test/features/commands/copyPathToClipboard.unit.test.ts
Labels: feature-request

#175 fix: wrap the experimental shell type API with try-catch
  src/features/common/shellDetector.ts
Labels: bug

#180 Move description of env managers to tooltip
  src/features/views/treeViewItems.ts
  src/managers/builtin/venvManager.ts
Labels: bug

#178 fix: use '/' delimiter on windows when using gitbash.
  src/common/utils/unsafeEntries.ts
  src/features/common/shellDetector.ts
  src/managers/builtin/venvUtils.ts
  src/managers/conda/condaUtils.ts
  src/test/features/common/shellDetector.unit.test.ts
Labels: bug

#183 bug: reduce noise in the environments view
  src/features/views/treeViewItems.ts
  src/managers/builtin/sysPythonManager.ts
  src/managers/builtin/utils.ts
  src/managers/builtin/venvManager.ts
  src/managers/builtin/venvUtils.ts
  src/managers/conda/condaEnvManager.ts
  src/managers/conda/condaUtils.ts
Labels: bug
